name: Update README Weather

on:
  schedule:
    # GitHub cron uses UTC. 12:00 UTC ≈ 14:00 in Ljubljana (CEST, summer time).
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Update README.md weather section
        id: update
        shell: bash
        run: |
          set -euo pipefail

          readonly FILE="README.md"
          readonly URL='https://wttr.in/~Nemci,%20Slovenija?T&m'
          readonly MARKER='^Weather report:'
          error() { echo "$@" >&2; exit 1; }

          weather="$(mktemp)"
          trap 'rm -f "${weather}"' EXIT

          curl -fsSL "${URL}" | head -n7 > "${weather}" ||
            error "Failed to fetch weather"

          grep -q "${MARKER}" "${weather}" ||
            error "Weather fetch returned unexpected content"

          start_line="$(grep -n -m1 "${MARKER}" "${FILE}" | cut -d: -f1)" ||
            error "Could not find '${MARKER}' in ${FILE}"
          end_line=$(( start_line + 6 ))

          # Replace lines [start_line..end_line] with the freshly fetched weather block
          awk -v s="${start_line}" -v e="${end_line}" -v f="${weather}" '
            NR == s {
              while ((getline line < f) > 0) print line;
              close(f);
              next
            }
            NR > s && NR <= e { next }
            { print }
          ' "${FILE}" > "${FILE}.tmp"

          if cmp -s "${FILE}" "${FILE}.tmp"; then
            echo "README.md already up-to-date."
            rm -f "${FILE}.tmp"
            echo "no_changes=true" >> "${GITHUB_OUTPUT}"
          else
            mv "${FILE}.tmp" "${FILE}"
            echo "Updated README.md weather block."
            echo "no_changes=false" >> "${GITHUB_OUTPUT}"
          fi

      - name: Commit and push changes (if any)
        if: steps.update.outputs.no_changes == 'false'
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore(readme): daily weather update (Bled, SI)"
          git push